### ISSUE TITLE
method updateActivityNode(node) returns org.apache.xerces.dom.DeferredElementNSImpl incompatible with org.w3c.dom.Document

### ISSUE THREAD

**Issue by ShirouWrath** [OpenNTF/SocialSDK#1612] opened 2014-08-11 14:50 UTC
Simple snippet called from JS returns org.apache.xerces.dom.DeferredElementNSImpl incompatible with org.w3c.dom.Document error. 

In my case In Activity and ActivityNodes exists, cause i got valid id result on my editbox.

Snippet:
var activityService = new com.ibm.sbt.services.client.connections.activity.ActivityService();
var activityId = activityService.getMyActivities().get(0).getActivityId();
var todoNode = activityService.getActivityNodes(activityId).get(0);
getComponent("responseBox").setValue(todoNode.getActivityId());
activityService.updateActivityNode(todoNode);

Tested on:
IBM Connections: v5 (corporate) and Greenhouse,
IBM SBT SDK: 1.0.3.20140723-1200,
Execution context: Domino Release 9.0.1HF25

**Comment by prb112** [comment] 2015-05-11 21:08
it'd be more helpful if you got the xpages logs referenced in your screenshot. however, the issue is most likely that you are not getting a XML document back (as expected), you are most likely getting an html page back.  I am closing this as invalid

**Closed by prb112** 2015-05-11 21:08 UTC
Labels: invalid, question
